# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './src/gui/qt/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 480))
        font = QtGui.QFont()
        font.setPointSize(8)
        MainWindow.setFont(font)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.btn_scan = QtWidgets.QPushButton(self.centralWidget)
        self.btn_scan.setGeometry(QtCore.QRect(0, 10, 81, 41))
        self.btn_scan.setObjectName("btn_scan")
        self.table_eaten_today = QtWidgets.QTableWidget(self.centralWidget)
        self.table_eaten_today.setGeometry(QtCore.QRect(90, 10, 701, 411))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_eaten_today.sizePolicy().hasHeightForWidth())
        self.table_eaten_today.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.table_eaten_today.setFont(font)
        self.table_eaten_today.setObjectName("table_eaten_today")
        self.table_eaten_today.setColumnCount(8)
        self.table_eaten_today.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_eaten_today.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_eaten_today.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_eaten_today.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_eaten_today.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_eaten_today.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_eaten_today.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_eaten_today.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_eaten_today.setHorizontalHeaderItem(7, item)
        self.table_eaten_today.horizontalHeader().setDefaultSectionSize(85)
        self.table_eaten_today.horizontalHeader().setStretchLastSection(False)
        self.table_eaten_today.verticalHeader().setDefaultSectionSize(20)
        self.table_eaten_today.verticalHeader().setMinimumSectionSize(20)
        self.btn_search = QtWidgets.QPushButton(self.centralWidget)
        self.btn_search.setGeometry(QtCore.QRect(0, 60, 81, 41))
        self.btn_search.setObjectName("btn_search")
        self.btn_delete = QtWidgets.QPushButton(self.centralWidget)
        self.btn_delete.setGeometry(QtCore.QRect(0, 110, 81, 41))
        self.btn_delete.setObjectName("btn_delete")
        self.calendar = QtWidgets.QCalendarWidget(self.centralWidget)
        self.calendar.setEnabled(True)
        self.calendar.setGeometry(QtCore.QRect(110, 40, 528, 359))
        self.calendar.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Finland))
        self.calendar.setGridVisible(False)
        self.calendar.setSelectionMode(QtWidgets.QCalendarWidget.SingleSelection)
        self.calendar.setObjectName("calendar")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Food tracker"))
        self.btn_scan.setText(_translate("MainWindow", "Scan"))
        item = self.table_eaten_today.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Code"))
        item = self.table_eaten_today.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.table_eaten_today.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Amount"))
        item = self.table_eaten_today.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Cals"))
        item = self.table_eaten_today.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Prot"))
        item = self.table_eaten_today.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Carbs (sug)"))
        item = self.table_eaten_today.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Fat (sat)"))
        item = self.table_eaten_today.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Salt"))
        self.btn_search.setText(_translate("MainWindow", "Search"))
        self.btn_delete.setText(_translate("MainWindow", "Delete"))

